"""Generate runtime/unicode_tables.h: the character classes and NFC data the C tokenizer needs.

    python ports/jibo/tools/gen_unicode_tables.py > ports/jibo/runtime/unicode_tables.h

The classes come from the tokenizer itself, not from a Unicode database: `tokenizers` splits
text with Oniguruma, whose Unicode version is newer than Python's, so `\\p{L}`, `\\p{N}` and
`\\s` are read off by asking a Split pre-tokenizer which codepoints each class matches. NFC
data comes from Python's `unicodedata`; every single codepoint normalises the same under it
and under `tokenizers.normalizers.NFC` (checked below). Python's own whitespace set, which
`str.strip` and `str.split` use when prompting.py renders a question, is a separate table.
"""

from __future__ import annotations

import sys
import unicodedata

from tokenizers import Regex, normalizers, pre_tokenizers

CODEPOINTS = [c for c in range(1, 0x110000) if not 0xD800 <= c <= 0xDFFF]
# Hangul syllables compose and decompose algorithmically; the C code handles them.
S_BASE, L_BASE, V_BASE, T_BASE = 0xAC00, 0x1100, 0x1161, 0x11A7
L_COUNT, V_COUNT, T_COUNT = 19, 21, 28
S_COUNT = L_COUNT * V_COUNT * T_COUNT


def onig_class(pattern: str) -> set[int]:
    """Codepoints the pattern matches, as the tokenizer's regex engine sees them."""
    text = "".join(map(chr, CODEPOINTS))
    kept = bytearray(len(text))
    for _, (a, b) in pre_tokenizers.Split(Regex(pattern), behavior="removed").pre_tokenize_str(text):
        kept[a:b] = b"\x01" * (b - a)
    return {CODEPOINTS[i] for i in range(len(text)) if not kept[i]}


def ranges(cps: set[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for c in sorted(cps):
        if out and out[-1][1] == c - 1:
            out[-1] = (out[-1][0], c)
        else:
            out.append((c, c))
    return out


def check_nfc_agrees() -> None:
    sep = "\x00"
    ours = normalizers.NFC().normalize_str(sep.join(map(chr, CODEPOINTS))).split(sep)
    bad = [c for c, o in zip(CODEPOINTS, ours, strict=True) if o != unicodedata.normalize("NFC", chr(c))]
    if bad:
        raise SystemExit(f"tokenizers and unicodedata disagree on NFC for {len(bad)} codepoints: {bad[:5]}")


def emit_ranges(name: str, rs: list[tuple[int, int]]) -> None:
    print(f"static const jd_range {name}[{len(rs)}] = {{")
    for i in range(0, len(rs), 6):
        print("  " + " ".join(f"{{0x{a:X},0x{b:X}}}," for a, b in rs[i:i + 6]))
    print("};")


def main() -> None:
    check_nfc_agrees()
    letters, numbers, spaces = onig_class(r"\p{L}"), onig_class(r"\p{N}"), onig_class(r"\s")
    marks = onig_class(r"\p{M}")
    py_space = {c for c in CODEPOINTS if chr(c).isspace()}

    ccc = {c: unicodedata.combining(chr(c)) for c in CODEPOINTS if unicodedata.combining(chr(c))}
    decomp: dict[int, list[int]] = {}
    for c in CODEPOINTS:
        if S_BASE <= c < S_BASE + S_COUNT:
            continue
        d = unicodedata.decomposition(chr(c))
        if d and not d.startswith("<"):
            decomp[c] = [int(x, 16) for x in d.split()]
    # Primary composites: canonical pairs that NFC recomposes (excludes singletons and the
    # composition exclusions, which NFC leaves decomposed).
    compose = {}
    for c, d in decomp.items():
        if len(d) == 2 and unicodedata.normalize("NFC", chr(d[0]) + chr(d[1])) == chr(c):
            compose[(d[0], d[1])] = c

    print("/* Generated by ports/jibo/tools/gen_unicode_tables.py. Do not edit. */")
    print(f"/* Python unicodedata {unicodedata.unidata_version}; classes read from the tokenizers regex engine. */")
    print("#ifndef JD_UNICODE_TABLES_H\n#define JD_UNICODE_TABLES_H\n#include <stdint.h>")
    print("typedef struct { uint32_t lo, hi; } jd_range;")
    print("typedef struct { uint32_t cp; uint8_t ccc; } jd_ccc;")
    print("typedef struct { uint32_t cp, a, b; } jd_decomp; /* b == 0 for a singleton */")
    print("typedef struct { uint32_t a, b, c; } jd_comp;")
    print(f"#define JD_HANGUL_S_BASE 0x{S_BASE:X}\n#define JD_HANGUL_L_BASE 0x{L_BASE:X}")
    print(f"#define JD_HANGUL_V_BASE 0x{V_BASE:X}\n#define JD_HANGUL_T_BASE 0x{T_BASE:X}")
    print(f"#define JD_HANGUL_L_COUNT {L_COUNT}\n#define JD_HANGUL_V_COUNT {V_COUNT}")
    print(f"#define JD_HANGUL_T_COUNT {T_COUNT}\n#define JD_HANGUL_S_COUNT {S_COUNT}")
    emit_ranges("jd_letter_ranges", ranges(letters))
    emit_ranges("jd_mark_ranges", ranges(marks))
    emit_ranges("jd_number_ranges", ranges(numbers))
    emit_ranges("jd_space_ranges", ranges(spaces))
    emit_ranges("jd_pyspace_ranges", ranges(py_space))
    items = sorted(ccc.items())
    print(f"static const jd_ccc jd_ccc_table[{len(items)}] = {{")
    for i in range(0, len(items), 8):
        print("  " + " ".join(f"{{0x{c:X},{v}}}," for c, v in items[i:i + 8]))
    print("};")
    ds = sorted(decomp.items())
    print(f"static const jd_decomp jd_decomp_table[{len(ds)}] = {{")
    for i in range(0, len(ds), 4):
        print("  " + " ".join(f"{{0x{c:X},0x{d[0]:X},0x{d[1] if len(d) > 1 else 0:X}}}," for c, d in ds[i:i + 4]))
    print("};")
    cs = sorted(compose.items())
    print(f"static const jd_comp jd_comp_table[{len(cs)}] = {{")
    for i in range(0, len(cs), 4):
        print("  " + " ".join(f"{{0x{a:X},0x{b:X},0x{c:X}}}," for (a, b), c in cs[i:i + 4]))
    print("};")
    print("#endif")
    print(f"letters {len(letters)} marks {len(marks)} numbers {len(numbers)} spaces {len(spaces)} pyspace {len(py_space)} "
          f"ccc {len(ccc)} decomp {len(decomp)} compose {len(compose)}", file=sys.stderr)


if __name__ == "__main__":
    main()
